### PR TITLE
Fix proposal standings are being set to `New Project`

### LINKED ISSUE #81: Proposals are being set to `New Project` even though former proposals exist for the project
Proposals are being set to `New Project` even though former proposals exist for the project

### PR DESCRIPTION
**Pull request by trizin**
Fixes #81.

Changes proposed in this PR:

- When processing current round proposals we should pass all proposals to the function so it can check whether a former proposal exists for a project.
- Added `extraProposals` optional argument to `processProposalStandings` function. Concatenating the current round proposals with all proposals.

### CODE REVIEW

File: src/airtable/proposals/proposal_standings.js [hunk 1]
```diff
@@ -187,12 +187,15 @@ const getProposalRecord = async (proposal, allProposals) => {
 }
 
 // Returns all Proposal Standings, indexed by Project Name
-const processProposalStandings = async (allProposals) => {
+const processProposalStandings = async (allProposals, extraProposals = []) => {
```
Comment (AnaLoznianu) [inline src/airtable/proposals/proposal_standings.js:190]: Please rename these parameters. It's difficult to understand extraProposals. I imagine they are representing currentRoundProposals and previousRoundsProposals

**Review by AnaLoznianu — APPROVED** [review]

File: src/airtable/proposals/proposal_standings.js (hunk 1 above)
Comment (trizin) [reply src/airtable/proposals/proposal_standings.js:190]: I agree, thanks for pointing that out!

**Review by AnaLoznianu — APPROVED** [review]

**Review by KatunaNorbert — APPROVED** [review]
Looks good!
