### PR TITLE
Report no standings fix no ocean proposal standings

### LINKED ISSUE #12: [DAOBot] Fix [Proposal Standing] to properly verify "No Ocean", and report projects without a standing.
DAOBot executes [process_airtable_all_proposal_standings.js](https://github.com/oceanprotocol/DAOBot/blob/main/src/airtable/process_airtable_all_proposal_standings.js) in order to update all project standings.

The tests located inside [test_airtable_proposal_standings.js](https://github.com/oceanprotocol/DAOBot/blob/main/src/test/airtable/test_airtable_proposal_standings.js) validate that all states/updates are executing properly, and should be used to verify that this update is working as intended.

#### DoD: New Project
- [x] Update proposal standing script so that it reports "New Project" for new projects that have not yet received a proposal standing. Currently, you can [look at Airtable](https://airtable.com/shrd5s7HSXc2vC1iC) and you'll notice that "New Entrants" and "Multilingual Ocean Marketplace" have a null "Proposal Standing".

#### DoD: Fix "No Ocean"
- [x] Fix proposal standing script to report "No Ocean" properly. If a previous entry did not have enough $OCEAN, then the next proposal will also report this. I believe [this function](https://github.com/oceanprotocol/DAOBot/blob/2590e217966d2231d8021557af417134b74759ae/src/airtable/proposals/proposal_standings.js#L150), which is used to propagate the correct bad/good state, might need some extra logic to properly handle this. This will be most easily addressed by creating a new set of tests, which initiates a proposal with "No Ocean" and submits another proposal that has ocean in the account. You can [look at this airtable view](https://airtable.com/shroD7AH5DSwPqk6D), to look at `Walkers Reserve Currency` to understand this issue.

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #12 .

### CODE REVIEW

File: src/test/config.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+const WALLET_ADDRESS_WITH_ENOUGH_OCEANS = process.env.WALLET_ADDRESS_WITH_ENOUGH_OCEANS
+const WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS = process.env.WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS
+
+module.exports = {WALLET_ADDRESS_WITH_ENOUGH_OCEANS, WALLET_ADDRESS_WITH_NOT_ENOUGH_OCEANS}
```
Comment (claudiaHash) [inline src/test/config.js:4]: I think we should have a new line at the end of this file, as a good practice.

**Comment by idiom-bytes** [comment]
Hi Norbert, thank you for expanding test coverage, in addition to improving their execution!

I gave it a brief review and I can see you made some great improvements, and likely fixing some bugs due missing `await` commands, in addition to clean up variable names, and functions, to make it all easier to follow along.

Great update!
