### PR TITLE
Fix snapshot proposal deployment

### LINKED ISSUE #115: Fix Proposal Validation & "Accepted" logic. Funding Round should not switch from "Due Dilligence" to "Voting" if no successful proposal deployment.
### Conclusion
I deployed R13 by fixing proposals so all their parameters were getting configured properly, in order for it to be submitted to Snapshot.

### Background
Proposals were not being deployed correctly and a critical error is happening... but the grant period can still change from "Due Dilligence" to "Voting"

### Problem
- DAOBot is not updating proposals successfully
src/snapshot/prepare_snapshot_received_proposals_airtable.js
- Proposal are being set to"Accepted" although their parameters are not being updated successfully.

1. Bad order of operations
```
// There was a proposal with invalid "Grant Deliverables" that was crashing the system
// All proposals should have their parameters validated, BEFORE being set to 'Accepted' enum
validateAccceptedProposal
```

2. Accepted proposals were not getting picked up
```
// Proposals are being set to "Accepted" so "Received" and "Rejected" proposals are not getting picked up
// "Rejected" proposals should count and retested so they may then be "Accepted"
const proposals = await getProposalsSelectQuery(
    `AND({Round} = "${curRoundNumber}", OR({Proposal State} = "Received", {Proposal State} = "Rejected"), "true")`
  )

```
3. These enums were not updated properly
```
// This code block needs to be maintained as new enums are added/removed and our logic changes.
const goodStanding =
          proposalStanding === Standings.Completed ||
          proposalStanding === Standings.Refunded ||
          proposalStanding === Standings.Undefined ||
          proposalStanding === Standings.Unreported ||
          proposalStanding === Standings.NewProject
```

4. Accepting proposals mean that they should be ready to be deployed to Snapshot.
These parameters were not getting set correctly for any proposals, so nothing was getting deployed.
```
// Proposals should only be getting Accepted when their Voting Starts, Voting Ends, Snapshot Block, and Deployment Ready parameters are updated properly.
fields: {
  'Proposal State': 'Accepted',
  'Voting Starts': voteStartTime,
  'Voting Ends': voteEndTime,
  'Snapshot Block': Number(estimatedBlockHeight),
  'Deployment Ready': 'Yes'
}
```

### DOD:
- [ ] Please review code and Proposal Validation => Accepted logic
- [ ] When a proposal is "Accepted" all required parameters downstream (i.e. Grant Deliverables, Voting Starts etc..) should all be in place
- [ ] If any parameter is missing, proposals should not be getting "Accepted"
- [ ] If no proposals were deployed to snapshot, then the funding round should not change from "Due Dilligence" to "Voting"

### PR DESCRIPTION
**Pull request by trizin**
Fixes #115.

Changes proposed in this PR:

- Fix good standing enums
- Fix proposal select query
- Remove unnecessary code
- Only fetch `Accepted` proposals and update them.

DAOBot is already setting valid & in good state proposals to `Accepted`, otherwise, it sets the proposal to `Rejected`. There is no need to set them to `Rejected` again.

### CODE REVIEW

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const prepareProposalsForSnapshot = async (curRound) => {
   // TODO-RA: Proposals are being set to "Accepted" ahead of time, and are not being found.
   // Changed to this for R13 to work => `AND({Round} = "${curRoundNumber}", OR({Proposal State} = "Accepted"), "true")`
   const proposals = await getProposalsSelectQuery(
-    `AND({Round} = "${curRoundNumber}", OR({Proposal State} = "Received", {Proposal State} = "Rejected"), "true")`
+    `AND({Round} = "${curRoundNumber}", {Proposal State} = "Accepted", "true")`
```
Comment (AnaLoznianu) [inline src/snapshot/prepare_snapshot_received_proposals_airtable.js:42]: Are we sure we want to change this? As far as I remember we decided that the initial state of a proposal to be 'Rejected'

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js [hunk 2]
```diff
@@ -51,45 +51,16 @@ const prepareProposalsForSnapshot = async (curRound) => {
...
-
-        // Please update enums as required
-        const goodStanding =
-          proposalStanding === Standings.Completed ||
-          proposalStanding === Standings.Refunded ||
-          proposalStanding === Standings.Undefined ||
-          proposalStanding === Standings.Unreported ||
-          proposalStanding === Standings.NewProject
-
-        if (hasEnoughOceans(wallet_0x) && goodStanding === true) {
```
Comment (AnaLoznianu) [inline src/snapshot/prepare_snapshot_received_proposals_airtable.js:67]: If a proposal initially didn't have the 500 oceans required and was therefore rejected, but then adds the 500 oceans, will its state be updated according to the new logic?

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js (hunk 1 above)
Comment (trizin) [reply src/snapshot/prepare_snapshot_received_proposals_airtable.js:42]: Only `Accepted` proposals will be included in the voting

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js (hunk 2 above)
Comment (trizin) [reply src/snapshot/prepare_snapshot_received_proposals_airtable.js:67]: This logic works when creating the Snapshot proposal. We don't need to check the 500 Oceans required here because Daobot checks that every minute and will set the proposal to `Rejected` state if the wallet doesn't have enough Ocean tokens.

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js [hunk 3]
```diff
@@ -51,45 +51,16 @@ const prepareProposalsForSnapshot = async (curRound) => {
...
-            fields: {
-              'Proposal State': 'Rejected',
-              'Voting Starts': null,
-              'Voting Ends': null,
-              'Snapshot Block': null,
-              'Deployment Ready': 'No'
-            }
-          })
+      recordsPayload.push({
+        id: proposal.id,
```
[the remark this answers is not in the document]
Comment (trizin) [reply src/snapshot/prepare_snapshot_received_proposals_airtable.js:55]: We don't need to check the 500 Oceans required here because Daobot checks that every minute and will set the proposal to Rejected state if the wallet doesn't have enough Ocean tokens.

File: src/snapshot/prepare_snapshot_received_proposals_airtable.js (hunk 2 above)
Comment (AnaLoznianu) [reply src/snapshot/prepare_snapshot_received_proposals_airtable.js:67]: Awesome, thanks for taking the time and explain this to me. You are right, this logic is run only when the proposal is created and everything should be set by then.

**Review by AnaLoznianu — APPROVED** [review]

**Comment by idiom-bytes** [comment]
Skipping test that is failing to submit this to main branch, and be able to deploy QV ballot.

**Comment by idiom-bytes** [comment]
Merging functionality to deploy R14 to snapshot
